#!/bin/bash
# ============================================================================
# Moch — mobile backend setup & control
# ============================================================================
# Turns a fresh `moch-backend` install into a running phone-ready backend:
#   • generates a persistent pairing token   (~/.config/moch-serve.env)
#   • installs systemd user units            (moch-serve.service + moch-cron.timer)
#   • installs the `moch` command            (~/.local/bin/moch)
#   • starts everything and prints a QR code to pair the mobile app
#
# Usage:
#   scripts/moch-serve.sh setup   # default; idempotent — safe to re-run
#   scripts/moch-serve.sh status
#   scripts/moch-serve.sh restart | stop
#   scripts/moch-serve.sh qr      # reprint the pairing QR + token
#   scripts/moch-serve.sh uninstall [--purge]
#
# Environment:
#   MOCH_PORT   port for the WebSocket server (default 9222, so a hermes
#               install on 9119 keeps working untouched)
#   MOCH_BIND   bind address (default 0.0.0.0 — the phone must reach it)
#
# The hermes internals stay as installed; this script only layers the mobile
# service on top and never touches a ~/.hermes install or its `hermes` command.
# ============================================================================

set -euo pipefail

MOCH_HOME="${HERMES_HOME:-$HOME/.moch}"
INSTALL_DIR="$MOCH_HOME/moch-backend"
MOCH_CMD="$INSTALL_DIR/.hermes/bin/hermes"
ENV_FILE="$HOME/.config/moch-serve.env"
UNIT_DIR="$HOME/.config/systemd/user"
BIN_DIR="$HOME/.local/bin"
MOCH_PORT="${MOCH_PORT:-9222}"
MOCH_BIND="${MOCH_BIND:-0.0.0.0}"
MOCH_COMMAND="${MOCH_COMMAND:-moch}"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'; CYAN='\033[0;36m'
BOLD='\033[1m'; NC='\033[0m'
log_info()    { echo -e "${CYAN}[moch]${NC} $*"; }
log_success() { echo -e "${GREEN}[moch ✓]${NC} $*"; }
log_warn()    { echo -e "${YELLOW}[moch !]${NC} $*"; }
log_error()   { echo -e "${RED}[moch ✗]${NC} $*" >&2; }

require_install() {
    if [ ! -x "$MOCH_CMD" ]; then
        log_error "No Moch install found at $INSTALL_DIR (missing .hermes/bin/hermes)."
        log_error "Run the installer first:  curl -fsSL <moch install.sh> | bash"
        exit 1
    fi
}

# The checkout launcher is `exec <store-python> -I -c <script>`; the managed
# interpreter in line 2 carries the dependency environment (incl. qrcode).
store_python() {
    local py
    py="$(sed -n "s/^exec '\([^']*\)' .*/\1/p" "$MOCH_CMD" 2>/dev/null | head -1)"
    if [ -n "$py" ] && [ -x "$py" ]; then
        printf '%s' "$py"
        return 0
    fi
    return 1
}

lan_ip() {
    ip -4 route get 1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}' \
        || hostname -I 2>/dev/null | awk '{print $1; exit}' \
        || echo "127.0.0.1"
}

ensure_token() {
    mkdir -p "$(dirname "$ENV_FILE")"
    chmod 700 "$(dirname "$ENV_FILE")"
    if [ -f "$ENV_FILE" ] && grep -q '^HERMES_DASHBOARD_SESSION_TOKEN=' "$ENV_FILE"; then
        log_info "Pairing token already present ($ENV_FILE)"
        return
    fi
    # Shell equivalent of secrets.token_urlsafe(32): 32 random bytes, base64url.
    local token
    token="$(head -c 32 /dev/urandom | base64 | tr '+/' '-_' | tr -d '=\n')"
    cat > "$ENV_FILE" <<EOF
# Moch backend secrets — generated by moch-serve.sh. Do not commit.
HERMES_DASHBOARD_SESSION_TOKEN=$token
EOF
    chmod 600 "$ENV_FILE"
    log_success "Generated new pairing token → $ENV_FILE"
}

token_value() { sed -n 's/^HERMES_DASHBOARD_SESSION_TOKEN=//p' "$ENV_FILE" | head -1; }

install_moch_command() {
    mkdir -p "$BIN_DIR"
    cat > "$BIN_DIR/$MOCH_COMMAND" <<EOF
#!/usr/bin/env bash
unset PYTHONPATH
unset PYTHONHOME
export HERMES_HOME="$MOCH_HOME"
exec "$MOCH_CMD" "\$@"
EOF
    chmod +x "$BIN_DIR/$MOCH_COMMAND"
    log_success "Installed \`$MOCH_COMMAND\` command → $BIN_DIR/$MOCH_COMMAND"
}

install_units() {
    mkdir -p "$UNIT_DIR"
    cat > "$UNIT_DIR/moch-serve.service" <<EOF
[Unit]
Description=Moch backend (WebSocket gateway for the Moch mobile app)
After=network-online.target
Wants=network-online.target

[Service]
EnvironmentFile=$ENV_FILE
Environment=HERMES_HOME=$MOCH_HOME
WorkingDirectory=$MOCH_HOME
ExecStart=$MOCH_CMD serve --host $MOCH_BIND --port $MOCH_PORT
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
EOF
    # Without the always-on messaging gateway, scheduled jobs tick from here.
    cat > "$UNIT_DIR/moch-cron.service" <<EOF
[Unit]
Description=Moch scheduled jobs (one cron tick)

[Service]
Type=oneshot
EnvironmentFile=$ENV_FILE
Environment=HERMES_HOME=$MOCH_HOME
WorkingDirectory=$MOCH_HOME
ExecStart=$MOCH_CMD cron tick
EOF
    cat > "$UNIT_DIR/moch-cron.timer" <<EOF
[Unit]
Description=Run Moch cron ticks every minute

[Timer]
OnBootSec=90
OnCalendar=*-*-* *:*:00
AccuracySec=15
Persistent=true

[Install]
WantedBy=timers.target
EOF
    systemctl --user daemon-reload
    log_success "Installed systemd user units (moch-serve, moch-cron.timer)"
}

port_open() {
    (exec 3<>"/dev/tcp/127.0.0.1/$1" && exec 3>&-) 2>/dev/null
}

start_services() {
    systemctl --user enable --now moch-serve.service >/dev/null 2>&1 \
        || systemctl --user restart moch-serve.service
    systemctl --user enable --now moch-cron.timer >/dev/null 2>&1 \
        || systemctl --user restart moch-cron.timer
    local i
    for i in $(seq 1 30); do
        if port_open "$MOCH_PORT"; then
            log_success "Moch backend is up on port $MOCH_PORT"
            return 0
        fi
        sleep 1
    done
    log_warn "Port $MOCH_PORT not accepting yet — recent logs:"
    journalctl --user -u moch-serve.service -n 15 --no-pager 2>/dev/null || true
    return 1
}

print_qr() {
    local host token py
    host="$(lan_ip)"
    token="$(token_value)"
    echo
    echo -e "${BOLD}═══════════════════════ Moch is ready ═══════════════════════${NC}"
    echo
    if py="$(store_python)"; then
        "$py" -I - <<PY
import qrcode
payload = "moch://pair?host=$host&port=$MOCH_PORT&tls=0&token=$token"
qr = qrcode.QRCode(border=1)
qr.add_data(payload)
qr.print_ascii(invert=True)
PY
    else
        log_warn "Managed python not found — printing text pairing only."
    fi
    echo " Scan this in the Moch app — or enter manually:"
    echo -e "   Host:  ${BOLD}$host:$MOCH_PORT${NC}"
    echo -e "   Token: ${BOLD}$token${NC}"
    echo
    echo " On your Tailnet? Use the machine's tailscale hostname instead, and"
    echo " expose it securely:   tailscale serve --bg tcp:$MOCH_PORT"
    echo
    echo " Next steps:"
    echo "   moch auth login    # add a model provider key (needed before chatting)"
    echo "   moch qr            # show this QR again anytime"
    echo "   moch status        # backend health"
    echo -e "${BOLD}═════════════════════════════════════════════════════════════${NC}"
}

cmd_setup() {
    require_install
    ensure_token
    install_moch_command
    if command -v systemctl >/dev/null 2>&1 && systemctl --user show-environment >/dev/null 2>&1; then
        install_units
        start_services
    else
        log_warn "systemd --user unavailable — skipping service install."
        log_warn "Run the backend manually:  HERMES_HOME=$MOCH_HOME $MOCH_CMD serve --host $MOCH_BIND --port $MOCH_PORT"
    fi
    print_qr
}

cmd_status() {
    require_install
    echo -e "${BOLD}moch backend${NC}  (home: $MOCH_HOME)"
    if systemctl --user is-active --quiet moch-serve.service 2>/dev/null; then
        log_success "moch-serve.service active"
    else
        log_warn "moch-serve.service inactive (see: journalctl --user -u moch-serve.service -n 30)"
    fi
    if systemctl --user is-active --quiet moch-cron.timer 2>/dev/null; then
        log_success "moch-cron.timer active"
    else
        log_warn "moch-cron.timer inactive"
    fi
    port_open "$MOCH_PORT" && log_success "port $MOCH_PORT accepting connections" \
        || log_warn "port $MOCH_PORT not accepting"
}

cmd_restart() { require_install; systemctl --user restart moch-serve.service && log_success "restarted"; }
cmd_stop()    { systemctl --user stop moch-serve.service moch-cron.timer && log_success "stopped"; }

cmd_uninstall() {
    systemctl --user disable --now moch-serve.service moch-cron.timer >/dev/null 2>&1 || true
    rm -f "$UNIT_DIR/moch-serve.service" "$UNIT_DIR/moch-cron.service" "$UNIT_DIR/moch-cron.timer"
    systemctl --user daemon-reload >/dev/null 2>&1 || true
    rm -f "$BIN_DIR/$MOCH_COMMAND"
    log_success "Removed services and the \`$MOCH_COMMAND\` command."
    if [ "${1:-}" = "--purge" ]; then
        log_warn "Deleting $MOCH_HOME (all sessions, config, history!)"
        rm -rf "$MOCH_HOME"
    else
        log_info "Data kept at $MOCH_HOME — re-run setup anytime, or pass --purge to delete."
    fi
}

case "${1:-setup}" in
    setup)     cmd_setup ;;
    status)    cmd_status ;;
    restart)   cmd_restart ;;
    stop)      cmd_stop ;;
    qr)        require_install; print_qr ;;
    uninstall) shift; cmd_uninstall "${1:-}" ;;
    *) echo "Usage: moch-serve.sh {setup|status|restart|stop|qr|uninstall [--purge]}"; exit 1 ;;
esac
