#!/bin/bash
# ============================================================================
# Moch — mobile backend setup & control
# ============================================================================
# Turns a fresh `moch-backend` install into a running phone-ready backend:
#   • generates a persistent pairing token   (~/.config/moch-serve.env)
#   • installs systemd user units:
#       moch-serve.service  — `serve` on 127.0.0.1:<port> (token auth is
#                             loopback-only in hermes >= 0.21.3)
#       moch-proxy.service  — scripts/moch-proxy.js on 0.0.0.0:<proxy-port>,
#                             rewriting Host so phones on LAN/Tailnet can pair
#       moch-cron.timer     — one `cron tick` per minute (scheduled jobs
#                             without the always-on messaging gateway)
#   • installs the `moch` command            (~/.local/bin/moch)
#   • starts everything and prints a QR code to pair the mobile app
#
# Usage:
#   scripts/moch-serve.sh setup   # default; idempotent — safe to re-run
#   scripts/moch-serve.sh status | restart | stop
#   scripts/moch-serve.sh qr      # reprint the pairing QR + token
#   scripts/moch-serve.sh uninstall [--purge]
#
# Environment:
#   MOCH_PORT        backend port on loopback   (default 9222)
#   MOCH_PROXY_PORT  phone-facing proxy port    (default 9223)
#
# The hermes internals stay as installed; this script only layers the mobile
# service on top and never touches a ~/.hermes install or its `hermes` command.
# ============================================================================

set -euo pipefail

MOCH_HOME="${HERMES_HOME:-$HOME/.moch}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="$MOCH_HOME/moch-backend"
MOCH_CMD="$INSTALL_DIR/.hermes/bin/hermes"
ENV_FILE="$HOME/.config/moch-serve.env"
UNIT_DIR="$HOME/.config/systemd/user"
BIN_DIR="$HOME/.local/bin"
MOCH_PORT="${MOCH_PORT:-9222}"
MOCH_PROXY_PORT="${MOCH_PROXY_PORT:-9223}"
MOCH_COMMAND="${MOCH_COMMAND:-moch}"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'; CYAN='\033[0;36m'
BOLD='\033[1m'; NC='\033[0m'
log_info()    { echo -e "${CYAN}[moch]${NC} $*"; }
log_success() { echo -e "${GREEN}[moch ✓]${NC} $*"; }
log_warn()    { echo -e "${YELLOW}[moch !]${NC} $*"; }
log_error()   { echo -e "${RED}[moch ✗]${NC} $*" >&2; }

require_install() {
    if [ ! -x "$MOCH_CMD" ]; then
        log_error "No Moch install found at $INSTALL_DIR (missing .hermes/bin/hermes)."
        log_error "Run the installer first:  curl -fsSL <moch install.sh> | bash"
        exit 1
    fi
}

# The checkout launcher is `exec <store-python> -I -c <script>` (path bare or
# quoted); the managed interpreter on that line carries the dependency
# environment under an HERMES_HOME-scoped tools prefix.
store_python() {
    local py
    py="$(awk '/^exec /{print $2; exit}' "$MOCH_CMD" 2>/dev/null)"
    py="${py%\'}"; py="${py#\'}"; py="${py%\"}"; py="${py#\"}"
    if [ -n "$py" ] && [ -x "$py" ]; then
        printf '%s' "$py"
        return 0
    fi
    return 1
}

# Node for the proxy: prefer the system one, else pm's managed runtime.
node_bin() {
    local n
    if n="$(command -v node)"; then printf '%s' "$n"; return 0; fi
    n="$(ls -d "$MOCH_HOME"/tools/node-*/bin/node 2>/dev/null | sort -V | tail -1)"
    if [ -n "$n" ] && [ -x "$n" ]; then printf '%s' "$n"; return 0; fi
    return 1
}

lan_ip() {
    ip -4 route get 1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}' \
        || hostname -I 2>/dev/null | awk '{print $1; exit}' \
        || echo "127.0.0.1"
}

ensure_token() {
    mkdir -p "$(dirname "$ENV_FILE")"
    chmod 700 "$(dirname "$ENV_FILE")"
    if [ -f "$ENV_FILE" ] && grep -q '^HERMES_DASHBOARD_SESSION_TOKEN=' "$ENV_FILE"; then
        log_info "Pairing token already present ($ENV_FILE)"
        return
    fi
    # Shell equivalent of secrets.token_urlsafe(32): 32 random bytes, base64url.
    local token
    token="$(head -c 32 /dev/urandom | base64 | tr '+/' '-_' | tr -d '=\n')"
    cat > "$ENV_FILE" <<EOF
# Moch backend secrets — generated by moch-serve.sh. Do not commit.
HERMES_DASHBOARD_SESSION_TOKEN=$token
EOF
    chmod 600 "$ENV_FILE"
    log_success "Generated new pairing token → $ENV_FILE"
}

token_value() { sed -n 's/^HERMES_DASHBOARD_SESSION_TOKEN=//p' "$ENV_FILE" | head -1; }

install_moch_command() {
    # npm/bun installs already put a `moch` shim on PATH (the package's bin);
    # writing ours too would leave two `moch` commands shadowing each other.
    if command -v "$MOCH_COMMAND" >/dev/null 2>&1; then
        log_info "\`$MOCH_COMMAND\` already on PATH ($(command -v "$MOCH_COMMAND")) — leaving it alone"
        return 0
    fi
    mkdir -p "$BIN_DIR"
    # Same routing as the npm shim: control subcommands → moch-serve.sh,
    # anything else → the backend's own CLI (moch auth login, moch cron …).
    cat > "$BIN_DIR/$MOCH_COMMAND" <<EOF
#!/usr/bin/env bash
case "\$1" in
  ""|setup|status|restart|stop|qr|import-hermes|uninstall) exec "$INSTALL_DIR/scripts/moch-serve.sh" "\$@" ;;
  *) export HERMES_HOME="$MOCH_HOME"; exec "$MOCH_CMD" "\$@" ;;
esac
EOF
    chmod +x "$BIN_DIR/$MOCH_COMMAND"
    log_success "Installed \`$MOCH_COMMAND\` command → $BIN_DIR/$MOCH_COMMAND"
}

install_units() {
    local node
    if ! node="$(node_bin)"; then
        log_error "No node found (system or managed) — the phone proxy needs it."
        exit 1
    fi
    mkdir -p "$UNIT_DIR"
    cat > "$UNIT_DIR/moch-serve.service" <<EOF
[Unit]
Description=Moch backend (WebSocket gateway for the Moch mobile app)
After=network-online.target
Wants=network-online.target

[Service]
EnvironmentFile=$ENV_FILE
Environment=HERMES_HOME=$MOCH_HOME
WorkingDirectory=$MOCH_HOME
ExecStart=$MOCH_CMD serve --host 127.0.0.1 --port $MOCH_PORT
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
EOF
    cat > "$UNIT_DIR/moch-proxy.service" <<EOF
[Unit]
Description=Moch phone proxy (LAN/Tailnet -> loopback, Host rewrite)
After=moch-serve.service
Wants=moch-serve.service

[Service]
Environment=PORT=$MOCH_PROXY_PORT
Environment=UPSTREAM_PORT=$MOCH_PORT
ExecStart=$node $INSTALL_DIR/scripts/moch-proxy.js
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
EOF
    # Without the always-on messaging gateway, scheduled jobs tick from here.
    cat > "$UNIT_DIR/moch-cron.service" <<EOF
[Unit]
Description=Moch scheduled jobs (one cron tick)

[Service]
Type=oneshot
EnvironmentFile=$ENV_FILE
Environment=HERMES_HOME=$MOCH_HOME
WorkingDirectory=$MOCH_HOME
ExecStart=$MOCH_CMD cron tick
EOF
    cat > "$UNIT_DIR/moch-cron.timer" <<EOF
[Unit]
Description=Run Moch cron ticks every minute

[Timer]
OnBootSec=90
OnCalendar=*-*-* *:*:00
AccuracySec=15
Persistent=true

[Install]
WantedBy=timers.target
EOF
    systemctl --user daemon-reload
    log_success "Installed systemd user units (moch-serve, moch-proxy, moch-cron.timer)"
    # User units only run at boot while the user has a session — or lingering.
    if ! loginctl show-user "$USER" --property=Linger 2>/dev/null | grep -q '^Linger=yes'; then
        log_info "Headless server? Enable boot startup with:  sudo loginctl enable-linger $USER"
    fi
}

port_open() {
    (exec 3<>"/dev/tcp/127.0.0.1/$1" && exec 3>&-) 2>/dev/null
}

start_services() {
    # Always restart when units were rewritten: `enable --now` alone leaves an
    # already-running service on its old ExecStart/env (seen with a bind change).
    systemctl --user enable moch-serve.service moch-proxy.service moch-cron.timer >/dev/null 2>&1 || true
    systemctl --user restart moch-serve.service moch-proxy.service
    systemctl --user start moch-cron.timer >/dev/null 2>&1 || true
    local i
    for i in $(seq 1 30); do
        if port_open "$MOCH_PORT" && port_open "$MOCH_PROXY_PORT"; then
            log_success "Moch backend up: loopback:$MOCH_PORT, phone-facing :$MOCH_PROXY_PORT"
            return 0
        fi
        sleep 1
    done
    log_warn "Ports not accepting yet — recent logs:"
    journalctl --user -u moch-serve.service -u moch-proxy.service -n 15 --no-pager 2>/dev/null || true
    return 1
}

print_qr() {
    local host token py
    host="$(lan_ip)"
    token="$(token_value)"
    echo -e "${BOLD}═══════════════════════ Moch is ready ═══════════════════════${NC}"
    echo
    # Vendored dependency-free generator (scripts/vendor/qrcodegen.py, MIT,
    # © Project Nayuki) — any python3 renders it; failure never hides the token.
    py="$(store_python || command -v python3 || true)"
    if [ -n "$py" ]; then
        "$py" - "$SCRIPT_DIR/vendor" "$host" "$MOCH_PROXY_PORT" "$token" <<'PY' \
            || log_warn "QR rendering failed — pair with the text values below"
import sys
sys.path.insert(0, sys.argv[1])
from qrcodegen import QrCode
payload = "hermes://connect?host=%s:%s&tls=0&token=%s" % tuple(sys.argv[2:5])
qr = QrCode.encode_text(payload, QrCode.Ecc.MEDIUM)
b, get = qr.get_size(), qr.get_module
for y in range(-2, b + 2, 2):
    print("".join(
        "█" if (get(x, y) if 0 <= x < b and 0 <= y < b else False)
             and (get(x, y + 1) if 0 <= x < b and 0 <= y + 1 < b else False)
        else "▀" if (get(x, y) if 0 <= x < b and 0 <= y < b else False)
        else "▄" if (get(x, y + 1) if 0 <= x < b and 0 <= y + 1 < b else False)
        else " "
        for x in range(-2, b + 2)))
PY
    else
        log_warn "No python found — printing text pairing only."
    fi
    echo " Scan this in the Moch app — or enter manually:"
    echo -e "   Host:  ${BOLD}$host:$MOCH_PROXY_PORT${NC}"
    echo -e "   Token: ${BOLD}$token${NC}"
    echo -e "   Link:  ${BOLD}hermes://connect?host=$host:$MOCH_PROXY_PORT&tls=0&token=$token${NC}"
    echo
    echo " On your Tailnet? Use the machine's tailscale hostname instead, and"
    echo " expose it securely:   tailscale serve --bg tcp:$MOCH_PROXY_PORT"
    echo
    echo " Next steps:"
    echo "   moch auth login    # add a model provider key (needed before chatting)"
    echo "   moch qr            # show this QR again anytime"
    echo "   moch status        # backend health"
    echo -e "${BOLD}═════════════════════════════════════════════════════════════${NC}"
}

# First run on a machine that already has Hermes: offer to bring its data over.
maybe_offer_hermes_import() {
    [ -d "$HOME/.hermes" ] || return 0
    [ -f "$MOCH_HOME/auth.json" ] && return 0   # already imported / own auth
    echo
    log_info "Found an existing Hermes install at ~/.hermes."
    if [ -t 0 ] && (: </dev/tty) 2>/dev/null; then
        local answer
        printf "%s Import its providers, skills, memories, cron jobs and sessions? [Y/n] " "$(printf '%s[moch]%s' "$CYAN" "$NC")"
        read -r answer </dev/tty || answer="y"
        case "$answer" in
            n*|N*)
                log_info "Skipped. Import later anytime with:  moch import-hermes"
                return 0 ;;
            *)
                bash "$SCRIPT_DIR/moch-import-hermes.sh" || true ;;
        esac
    else
        log_info "Import its data (providers/skills/memories/cron/sessions) with:"
        log_info "  moch import-hermes"
    fi
}

cmd_setup() {
    require_install
    ensure_token
    install_moch_command
    if command -v systemctl >/dev/null 2>&1 && systemctl --user show-environment >/dev/null 2>&1; then
        install_units
        start_services
    else
        log_warn "systemd --user unavailable — skipping service install."
        log_warn "Run the backend manually:  HERMES_HOME=$MOCH_HOME $MOCH_CMD serve --host 127.0.0.1 --port $MOCH_PORT"
    fi
    maybe_offer_hermes_import
    print_qr
}

cmd_status() {
    require_install
    echo -e "${BOLD}moch backend${NC}  (home: $MOCH_HOME)"
    local u ok=1
    for u in moch-serve.service moch-proxy.service moch-cron.timer; do
        if systemctl --user is-active --quiet "$u" 2>/dev/null; then
            log_success "$u active"
        else
            log_warn "$u inactive (see: journalctl --user -u $u -n 30)"
            ok=0
        fi
    done
    port_open "$MOCH_PORT" && log_success "loopback:$MOCH_PORT accepting" || { log_warn "loopback:$MOCH_PORT not accepting"; ok=0; }
    port_open "$MOCH_PROXY_PORT" && log_success "phone port :$MOCH_PROXY_PORT accepting" || { log_warn "phone port :$MOCH_PROXY_PORT not accepting"; ok=0; }
    [ "$ok" = 1 ] || exit 1
}

cmd_restart() { require_install; systemctl --user restart moch-serve.service moch-proxy.service && log_success "restarted"; }
cmd_stop()    { systemctl --user stop moch-serve.service moch-proxy.service moch-cron.timer && log_success "stopped"; }

cmd_uninstall() {
    systemctl --user disable --now moch-serve.service moch-proxy.service moch-cron.timer >/dev/null 2>&1 || true
    rm -f "$UNIT_DIR/moch-serve.service" "$UNIT_DIR/moch-proxy.service" \
          "$UNIT_DIR/moch-cron.service" "$UNIT_DIR/moch-cron.timer"
    systemctl --user daemon-reload >/dev/null 2>&1 || true
    rm -f "$BIN_DIR/$MOCH_COMMAND"
    log_success "Removed services and the \`$MOCH_COMMAND\` command."
    if [ "${1:-}" = "--purge" ]; then
        log_warn "Deleting $MOCH_HOME and $ENV_FILE (all sessions, config, history!)"
        rm -rf "$MOCH_HOME"
        rm -f "$ENV_FILE"
    else
        log_info "Data kept at $MOCH_HOME — re-run setup anytime, or pass --purge to delete."
    fi
}

case "${1:-setup}" in
    setup)     cmd_setup ;;
    status)    cmd_status ;;
    restart)   cmd_restart ;;
    stop)      cmd_stop ;;
    qr)        require_install; ensure_token; print_qr ;;
    import-hermes) shift; exec bash "$SCRIPT_DIR/moch-import-hermes.sh" "$@" ;;
    uninstall) shift; cmd_uninstall "${1:-}" ;;
    *) echo "Usage: moch-serve.sh {setup|status|restart|stop|qr|import-hermes|uninstall [--purge]}"; exit 1 ;;
esac
